# Generated by Django 4.0.6 on 2022-07-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiares',
            name='fnac',
        ),
        migrations.RemoveField(
            model_name='familiares',
            name='nomina',
        ),
        migrations.AddField(
            model_name='familiares',
            name='peso',
            field=models.FloatField(default=60),
        ),
        migrations.AddField(
            model_name='familiares',
            name='registro',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
