# Generated by Django 4.0.6 on 2022-07-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0002_remove_familiares_fnac_remove_familiares_nomina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiares',
            name='parentezco',
            field=models.CharField(default='', max_length=100),
        ),
    ]
